apply plugin: 'com.android.application'

android {
    namespace 'com.kemd.monthwidget'
    compileSdk 34

    defaultConfig {
        applicationId "com.kemd.monthwidget"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.0'
}
